[package]
name = "rsservices"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rshost"
path = "src/bin/main_host.rs"

[[bin]]
name = "rsworker"
path = "src/bin/main_worker.rs"

[dependencies]
nix = { version = "0.28.0", features = ["mqueue"] }
